package com.example.login_davidroldan.utils

object Constants {
        const val BASE_URL = "http://192.168.1.77:8080/Login_DavidRoldan-1.0-SNAPSHOT/"
        const val CUSTOMER_URL = "api/customers"
        const val CUSTOMERID_URL = "api/customers/{id}"
        const val ORDER_URL = "api/orders"
        const val ORDERID_URL = "api/orders/{id}"
        const val CONTENTTYPE = "Content-Type: application/json"
        const val ERROR = "Error"
        const val HASORDERS = "\nThe customer has orders"
        const val NO_PERMISION = "\nYou need admin permissions"
        const val SELECTED = "selected"
        const val ID = "id"
        const val FIRSTNAME = "first_name"
        const val LASTNAME = "last_name"
        const val EMAIL = "email"
        const val PHONE = "phone"
        const val DOB = "dob"
        const val TABLEID = "tableid"
        const val DATE = "date"
        const val CUSTOMERID = "customerid"
        const val TOTALDELETED = "Total deleted "
        const val OF = " of "
        const val CUSTOMERDELETED = "Customer deleted"
        const val ORDERADDED = "Order added successfully"
        const val ERRORADDINGORDER = "Error adding order"
        const val ORDERDELETED = "Order deleted"
        const val NO_HAY_INTERNET = "No hay Internet, cargando de cache."
        const val DD_MM_YY = "dd-MM-yy"
        const val PASSWORD_CHANGED = "Password changed"
        const val NO_AUTOR_SELECCIONADO = "No hay autor seleccionado"
        const val LIBRO_ANYADIDO = "Libro añadido"
        const val SE_HA_ENVIADO_UN_CORREO = "Se ha enviado un correo a su cuenta"
        const val ROOT = "root"
        const val PASS2DAM = "2dam"
        const val RELLENE_TODOS_LOS_CAMPOS = "Rellene todos los campos"
        const val ACTIVE_SU_CUENTA = "Cuenta creada, actívela en el correo"
        const val USER_OR_TWOFA_EMPTY = "Usuario o Two-Factor code vacíos"
        const val USER_OR_PASS_EMPTY = "Usuario o contraseña vacíos"
        const val USER_EMPTY = "Usuario vacío"
}